const stocksData = [
    { symbol: "AAPL", name: "Apple Inc." },
    { symbol: "MSFT", name: "Microsoft Corporation" },
    { symbol: "GOOGL", name: "Alphabet Inc." },
    { symbol: "AMZN", name: "Amazon.com Inc." },
    { symbol: "TSLA", name: "Tesla Inc." },
    { symbol: "NFLX", name: "Netflix Inc." },
    { symbol: "META", name: "Meta Platforms Inc." },
    { symbol: "NVDA", name: "NVIDIA Corporation" },
    { symbol: "IBM", name: "International Business Machines" },
    { symbol: "INTC", name: "Intel Corporation" },
    { symbol: "AMD", name: "Advanced Micro Devices" },
    { symbol: "ORCL", name: "Oracle Corporation" },
    { symbol: "PYPL", name: "PayPal Holdings Inc." },
    { symbol: "CSCO", name: "Cisco Systems Inc." },
    { symbol: "PEP", name: "PepsiCo Inc." },
    { symbol: "KO", name: "The Coca-Cola Company" },
    { symbol: "BA", name: "The Boeing Company" },
    { symbol: "DIS", name: "The Walt Disney Company" },
    { symbol: "SONY", name: "Sony Group Corporation" },
    { symbol: "ADBE", name: "Adobe Inc." },
    { symbol: "V", name: "Visa Inc." },
    { symbol: "MA", name: "Mastercard Incorporated" },
    { symbol: "JPM", name: "JPMorgan Chase & Co." },
    { symbol: "WMT", name: "Walmart Inc." },
    { symbol: "T", name: "AT&T Inc." },
    { symbol: "VZ", name: "Verizon Communications Inc." },
    { symbol: "XOM", name: "Exxon Mobil Corporation" },
    { symbol: "CVX", name: "Chevron Corporation" },
    { symbol: "PFE", name: "Pfizer Inc." },
    { symbol: "MRNA", name: "Moderna Inc." },
  ];
  export default stocksData